### PR TITLE
Added support for GNOME 40

### LINKED ISSUE #5: Gnome 40 Support?
Please consider updating the extension for Gnome 40 support. Thanks!

### PR DESCRIPTION
**Pull request by AntiKippi**
This extension seems to be well working on GNOME 40 (tested only on my machine, see screenshot below), so in order to support it and get rid of the "Version not supported" error message I added GNOME 40 to the supported versions.

This fixes #5.

screenshot_gnome40

### CODE REVIEW

**Comment by Tedium16** [comment]
I was able to edit the version number, and the extension works fine on gnome 41 on arch linux.

**Comment by AntiKippi** [comment]
Same for me, also included version 41 now.

**Comment by murilo-develop** [comment]
It's working out like a charm in Pop_OS! 21.10 | Gnome 40 (Cosmic shell)

**Comment by bhack** [comment]
Gnome 42 PR is available at https://github.com/maoschanz/sound-percentage-gs-extension/pull/8

**Pull request closed without merging**
